### ISSUE TITLE
Possible dangerous behaviour of buildRequestBody

### ISSUE THREAD

**Issue by popstas** [MartialGeek/transmission-api#2]
I have filtered array of some torrents and want to remove it.

This code removes all torrents existed in transmission:
``` php
$torrent_ids = array_map(function($torrent){
    return($torrent[\Martial\Transmission\API\Argument\Torrent\Get::ID]);
}, $torrentList);

$api->torrentRemove($sessionId, $torrent_ids, true);
```

`array_map` generate associative array like
``` php
array (
  19 => 20,
  28 => 29,
  31 => 32,
  32 => 33,
  50 => 51,
  65 => 66,
  71 => 72,
  86 => 90,
)
```

`buildRequestBody` generate request like
``` json
{"method":"torrent-remove","arguments":{"ids":{"19":20,"28":29,"31":32,"32":33,"50":51,"65":66,"71":72,"86":90},"delete-local-data":true}}
```
Transmission don't trowed exception, it treated requested ids as empty value and deleted all torrents.

I should use only non-associative arrays for ids, like
``` php
$torrent_ids = [];
foreach ($torrentList as $torrent) {
    $torrent_ids[] = $torrent[\Martial\Transmission\API\Argument\Torrent\Get::ID];
}

$api->torrentRemove($sessionId, $torrent_ids, true);
```

In this case `buildRequestBody` generate request like
``` json
{"method":"torrent-remove","arguments":{"ids":[20,29,32,33,51,66,72,90],"delete-local-data":true}}
```

I think that it is non-obvious behavior, it was my mistake and mistake of transmission, but api can prevent this mistake.

**Comment by MartialGeek** [comment]
Hello

Thank you for reporting this issue. I will fix it in some hours.

**Comment by MartialGeek** [comment]
I'm sorry, I can't reproduce this bug. Here is my test:

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$guzzle = new \GuzzleHttp\Client(['base_uri' => 'http://my-server:9091/transmission/rpc']);
$api = new \Martial\Transmission\API\RpcClient($guzzle, 'username', 'password');

$logger = new \Monolog\Logger('transmission');
$logger->pushHandler(new \Monolog\Handler\StreamHandler('php://stdout'));

$api->setLogger($logger);

$sessionId = '';

try {
    $api->sessionGet('');
} catch (\Martial\Transmission\API\CSRFException $e) {
    $sessionId = $e->getSessionId();
}

$torrentList = $api->torrentGet($sessionId, [], [
    \Martial\Transmission\API\Argument\Torrent\Get::ID,
    \Martial\Transmission\API\Argument\Torrent\Get::NAME
]);

$logger->debug('Torrent list.', ['list' => $torrentList]);

$ids = [];

foreach ($torrentList as $torrent) {
    $ids[] = $torrent['id'];
}

$api->torrentRemove($sessionId, $ids, true);
```
The associated logs:
```sh
2016-01-18 21:32:28] transmission.DEBUG: Request sent to the Transmission RPC API. {"request":"{\"method\":\"session-get\"}"} []
[2016-01-18 21:32:28] transmission.INFO: Invalid Transmission session ID. A new ID has been generated. {"session_id":"7iprx0lbHvJkgLIG0YAAZZqxcGSyykbqC3VDu6ukhVl2ggxF"} []
[2016-01-18 21:32:28] transmission.DEBUG: Request sent to the Transmission RPC API. {"request":"{\"method\":\"torrent-get\",\"arguments\":{\"fields\":[\"id\",\"name\"]}}"} []
[2016-01-18 21:32:28] transmission.DEBUG: Torrent list. {"list":[{"id":3,"name":"ubuntu-14.04.3-desktop-amd64.iso"},{"id":4,"name":"debian-8.2.0-amd64-CD-1.iso"}]} []
[2016-01-18 21:32:28] transmission.DEBUG: Request sent to the Transmission RPC API. {"request":"{\"method\":\"torrent-remove\",\"arguments\":{\"ids\":[3,4],\"delete-local-data\":true}}"} []
```
As you can see in the last log message, the array of torrent IDs are serialized to a valid JSON array.
[This test](https://github.com/MartialGeek/transmission-api/blob/master/tests/RpcClientTest.php#L706) ensures that this behaviour is applied.

Can you check out the last version of the library and inject a logger to confirm the requests format?

**Comment by popstas** [comment]
It serialized wrong if you tried to filter ids from $torrentList using array_map:
```
$torrent_ids = array_map(function($torrent){
    return($torrent[\Martial\Transmission\API\Argument\Torrent\Get::ID]);
}, $torrentList);
```

In this case request will be like this:
```
{"method":"torrent-remove","arguments":{"ids":{"0":3,"2":4},"delete-local-data":true}}
```

You can prevent this if you will check that array of ids non-associative.

**Comment by MartialGeek** [comment]
OK, json_encode considers an indexed array as a hash if the keys don't start from 0, or something like that.

To solve this problem and keep the backward compatibility, I will extract the values of the array in the methods that require an array of IDs. However, in a new major version, I will use an object (probably inherited from SplFixedArray) in order to keep a stronger type control.

**Comment by MartialGeek** [comment]
@popstas Can you review this PR please ? https://github.com/MartialGeek/transmission-api/pull/4

**Comment by MartialGeek** [comment]
Sorry I need to merge the PR. Don't hesitate to open a new issue if necessary.
