### ISSUE TITLE
Call to a member function debug() on null in vendor/martial/transmission-api/src/RpcClient.php on line 518

### ISSUE THREAD

**Issue by popstas** [MartialGeek/transmission-api#3]
I tried to execute example code, it fails on line [sessionGet](https://github.com/MartialGeek/transmission-api/blob/master/doc/examples.php#L63), $this->logger is null.
Now we need to execute $api->setLogger($logger) before any RpcClient operations.

**Comment by MartialGeek** [comment]
I was reading an article about injection of optional dependencies and I had a flash!
My daughter asked me for her baby bottle and I completely forgot to had checks if no logger was injected :p

This issue will be fixed for tomorrow.
