### ISSUE TITLE
buildRequestBody distinguishes string and integer ids

### ISSUE THREAD

**Issue by popstas** [MartialGeek/transmission-api#5]
Similar as in #2, buildRequestBody too much precise. Here's code that always return empty torrent list:
```
$torrent_ids = explode(' ', '1 2 3');
$api->torrentGet($sessionId, $torrent_ids);
```

buildRequestBody builds request like
```
{"method":"torrent-get","arguments":{"ids":["1","2","3"],"fields":["id"]}}
```
Transmission can't see ids, it assumes request like this:
```
{"method":"torrent-get","arguments":{"ids":[1,2,3],"fields":["id"]}}
```

So, I need to add integer cast to array to avoid this:
```
$cleaned_ids = array_map(function ($id) {
    return (int)$id;
}, $ids);
```

**Comment by MartialGeek** [comment]
Hi @popstas 

If the library checks in each method if the array contains only integers, I add an overhead even for those who already provide an array of integers. IMHO, the responsibility of passing the right argument types lies with the developer who uses the library. You're right when you mention your old issue, it's the same kind of problem.

I think it's time to create a new major version with stronger argument types. Typically the array of IDs will be removed in favour of traversable objects. These objects will take the array of IDs as argument and they will ensure that the format is consistent.

I keep this thread opened to follow the development of the new version. Let me know if you have any questions.

**Comment by MartialGeek** [comment]
@popstas You can read the PR #10

**Comment by MartialGeek** [comment]
@popstas More than a review, if you have the time, I would like you to install the version of the PR by modifying your composer.json:
"martial/transmission-api": "dev-torrent_id_list"

Then, if you follow the guide UPGRADE-2.0.md, you should be able to update your code to use the new version. Can you confirm that please?

Tell me if you can not help me for this task, I would understand ;)

**Comment by popstas** [comment]
Unfortunally, I have no time at this week (see my contribution activity :), but I will review your code and try to make upgrade later.

**Comment by MartialGeek** [comment]
I need to merge the PR. Please read the UPGRADE-2.0.md to help to upgrade your library. Open an issue if you need any help, or if you encounter any problems.

**Comment by popstas** [comment]
Today I upgraded my transmission-cli's engine to transmission-api 2.0 :)

**Comment by MartialGeek** [comment]
Great! I hope the upgrade was easy to achieve!
