### ISSUE TITLE
Undefined index: torrent-added in RpcClient::torrentAdd for duplicates

### ISSUE THREAD

**Issue by popstas** [MartialGeek/transmission-api#6]
This function returns `$response['arguments']['torrent-added']`.

Response may not contain `torrent-added` key, but contain `torrent-duplicate` key.

**Comment by popstas** [comment]
I think that return of `$response['arguments']` more correct in this case.

**Comment by MartialGeek** [comment]
Thank you for debugging my library ;)
I did not read this case in the doc of the Transmission RPC : https://trac.transmissionbt.com/browser/trunk/extras/rpc-spec.txt#L389
So I will fix it ASAP.

**Comment by MartialGeek** [comment]
I have just seen that I planned this error in my interface:
```php
@throws DuplicateTorrentException
```
I omitted to write the test...

**Comment by popstas** [comment]
Ok, exception more explicit in this case!

**Comment by MartialGeek** [comment]
OK @popstas you can check this PR: #9
