### ISSUE TITLE
freeSpace don't returns any data

### ISSUE THREAD

**Issue by popstas** [MartialGeek/transmission-api#7]
It just send request and have `@return` in phpdoc. Why unit tests not detected this? 

Maybe any code analyzers can detect this and similar error? PhpStorm and PHPMD not detects it.

**Comment by MartialGeek** [comment]
Unit tests don't detect this error because I forgot to implement this check :p
PHPStorm seems to only detect missing @return tag in the PHPDoc, and I don't remember the behavior of PHPMD about that.

**Comment by MartialGeek** [comment]
@popstas Can you read this PR please? #8
